import { db } from "./db";
import { people } from "@shared/schema";

async function seed() {
  console.log("Seeding database with family members...");

  const familyData = [
    // Husband
    {
      name: "Neil Barnett",
      category: "husband",
      relationship: "Husband",
      photoUrl: null,
      photoData: null,
      born: "September 22, 1935",
      age: null,
      passed: "April 24, 2025",
      location: "Potsdam, New York (originally)",
      spouse: null,
      children: ["Ted", "Jon", "Chris", "Mark"],
      summary: "Sailor, former director at Procter & Gamble, devoted husband and father",
      sortOrder: 1,
      lastVisit: null,
      visitHistory: null,
    },
    
    // Children (4 sons)
    {
      name: "Ted Barnett",
      category: "children",
      relationship: "Son",
      photoUrl: null,
      photoData: null,
      born: "June 10, 1962",
      age: 63,
      passed: null,
      location: "New York City",
      spouse: "Melanie Craft (fiancée)",
      children: ["Olivia", "Willa", "Ryan"],
      summary: "Computer developer building a 3D reconstruction of New York City",
      sortOrder: 1,
      lastVisit: null,
      visitHistory: null,
    },
    {
      name: "Jon Barnett",
      category: "children",
      relationship: "Son",
      photoUrl: null,
      photoData: null,
      born: "April 2, 1964",
      age: 61,
      passed: null,
      location: "Flathead Lake, Montana",
      spouse: "Denae Barnett",
      children: null,
      summary: "Superyacht designer",
      sortOrder: 2,
      lastVisit: null,
      visitHistory: null,
    },
    {
      name: "Chris Barnett",
      category: "children",
      relationship: "Son",
      photoUrl: null,
      photoData: null,
      born: "July 31, 1967",
      age: 58,
      passed: null,
      location: "Bainbridge Island, Washington",
      spouse: "Mary Beth Barnett",
      children: ["Sam", "Audrey"],
      summary: "Top salesman for StruXure (luxury outdoor pergolas)",
      sortOrder: 3,
      lastVisit: null,
      visitHistory: null,
    },
    {
      name: "Mark Barnett",
      category: "children",
      relationship: "Son",
      photoUrl: null,
      photoData: null,
      born: "May 31, 1970",
      age: 55,
      passed: null,
      location: "Loveland, Ohio",
      spouse: "Jill Barnett",
      children: ["Jack", "Charlie", "Nicholas"],
      summary: "Set designer for films, manages Loveland bar 'Hops & Berry' with Jill",
      sortOrder: 4,
      lastVisit: null,
      visitHistory: null,
    },

    // Grandchildren (8)
    {
      name: "Olivia Barnett",
      category: "grandchildren",
      relationship: "Granddaughter (Ted's daughter)",
      photoUrl: null,
      photoData: null,
      born: "June 22, 1996",
      age: 29,
      passed: null,
      location: "Porto, Portugal",
      spouse: "Blaine Malone (partner, programmer)",
      children: null,
      summary: "Software developer",
      sortOrder: 1,
      lastVisit: null,
      visitHistory: null,
    },
    {
      name: "Willa Barnett",
      category: "grandchildren",
      relationship: "Granddaughter (Ted's daughter)",
      photoUrl: null,
      photoData: null,
      born: "January 29, 1999",
      age: 26,
      passed: null,
      location: "Brooklyn, New York",
      spouse: "Leo (partner, NYU Law School)",
      children: null,
      summary: "Improv and stand-up comedian; web developer",
      sortOrder: 2,
      lastVisit: null,
      visitHistory: null,
    },
    {
      name: "Ryan Barnett",
      category: "grandchildren",
      relationship: "Grandson (Ted's son)",
      photoUrl: null,
      photoData: null,
      born: "January 10, 2001",
      age: 24,
      passed: null,
      location: "Brooklyn, New York",
      spouse: "Alyssa (girlfriend, photographer)",
      children: null,
      summary: "Filmmaker; editor at HBO",
      sortOrder: 3,
      lastVisit: null,
      visitHistory: null,
    },
    {
      name: "Jack Barnett",
      category: "grandchildren",
      relationship: "Grandson (Mark's son)",
      photoUrl: null,
      photoData: null,
      born: "April 24, 2001",
      age: null,
      passed: null,
      location: "Tampa, Florida",
      spouse: null,
      children: null,
      summary: "Software engineer, Chi Psi fraternity",
      sortOrder: 4,
      lastVisit: null,
      visitHistory: null,
    },
    {
      name: "Nicholas Barnett",
      category: "grandchildren",
      relationship: "Grandson (Mark's son)",
      photoUrl: null,
      photoData: null,
      born: "July 16, 2006",
      age: null,
      passed: null,
      location: "University of Kentucky",
      spouse: null,
      children: null,
      summary: "Freshman at University of Kentucky, Chi Psi fraternity",
      sortOrder: 5,
      lastVisit: null,
      visitHistory: null,
    },
    {
      name: "Charlie Barnett",
      category: "grandchildren",
      relationship: "Grandson (Mark's son)",
      photoUrl: null,
      photoData: null,
      born: "July 16, 2006",
      age: null,
      passed: null,
      location: "University of Kentucky",
      spouse: null,
      children: null,
      summary: "Freshman at University of Kentucky, Chi Psi fraternity",
      sortOrder: 6,
      lastVisit: null,
      visitHistory: null,
    },
    {
      name: "Sam Barnett",
      category: "grandchildren",
      relationship: "Grandson (Chris's son)",
      photoUrl: null,
      photoData: null,
      born: "May 31, 2001",
      age: null,
      passed: null,
      location: "Bainbridge Island, Washington",
      spouse: null,
      children: null,
      summary: "Supply Chain manager for Lockheed",
      sortOrder: 7,
      lastVisit: null,
      visitHistory: null,
    },
    {
      name: "Audrey Barnett",
      category: "grandchildren",
      relationship: "Granddaughter (Chris's daughter)",
      photoUrl: null,
      photoData: null,
      born: "August 29, 2003",
      age: null,
      passed: null,
      location: "Columbus, Ohio",
      spouse: null,
      children: null,
      summary: "Student at Ohio State University, studying Nursing",
      sortOrder: 8,
      lastVisit: null,
      visitHistory: null,
    },

    // Friends (2)
    {
      name: "Weezy Allen",
      category: "friends",
      relationship: "Friend",
      photoUrl: null,
      photoData: null,
      born: null,
      age: null,
      passed: null,
      location: null,
      spouse: "Widow of Tom Gougeon",
      children: null,
      summary: null,
      sortOrder: 1,
      lastVisit: null,
      visitHistory: null,
    },
    {
      name: "Lynn Murray",
      category: "friends",
      relationship: "Friend",
      photoUrl: null,
      photoData: null,
      born: null,
      age: null,
      passed: null,
      location: null,
      spouse: "Widow of Jack Murray",
      children: null,
      summary: null,
      sortOrder: 2,
      lastVisit: null,
      visitHistory: null,
    },

    // Caregivers (6)
    {
      name: "Paige",
      category: "caregivers",
      relationship: "Caregiver",
      photoUrl: null,
      photoData: null,
      born: null,
      age: null,
      passed: null,
      location: null,
      spouse: null,
      children: null,
      summary: null,
      sortOrder: 1,
      lastVisit: null,
      visitHistory: null,
    },
    {
      name: "Lei",
      category: "caregivers",
      relationship: "Caregiver",
      photoUrl: null,
      photoData: null,
      born: null,
      age: null,
      passed: null,
      location: null,
      spouse: null,
      children: null,
      summary: null,
      sortOrder: 2,
      lastVisit: null,
      visitHistory: null,
    },
    {
      name: "Kirstin",
      category: "caregivers",
      relationship: "Caregiver",
      photoUrl: null,
      photoData: null,
      born: null,
      age: null,
      passed: null,
      location: null,
      spouse: null,
      children: null,
      summary: null,
      sortOrder: 3,
      lastVisit: null,
      visitHistory: null,
    },
    {
      name: "Deborah",
      category: "caregivers",
      relationship: "Caregiver",
      photoUrl: null,
      photoData: null,
      born: null,
      age: null,
      passed: null,
      location: null,
      spouse: null,
      children: null,
      summary: null,
      sortOrder: 4,
      lastVisit: null,
      visitHistory: null,
    },
    {
      name: "Trish",
      category: "caregivers",
      relationship: "Caregiver",
      photoUrl: null,
      photoData: null,
      born: null,
      age: null,
      passed: null,
      location: null,
      spouse: null,
      children: null,
      summary: null,
      sortOrder: 5,
      lastVisit: null,
      visitHistory: null,
    },
    {
      name: "Barbara",
      category: "caregivers",
      relationship: "Caregiver",
      photoUrl: null,
      photoData: null,
      born: null,
      age: null,
      passed: null,
      location: null,
      spouse: null,
      children: null,
      summary: null,
      sortOrder: 6,
      lastVisit: null,
      visitHistory: null,
    },
  ];

  await db.insert(people).values(familyData);
  console.log("✅ Successfully seeded family members!");
}

// Export for use from routes.ts during app initialization
export async function seedDatabase() {
  return seed();
}

// Run seed directly if this file is executed as a script
if (import.meta.url === `file://${process.argv[1]}`) {
  seed().catch((error) => {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  }).then(() => {
    process.exit(0);
  });
}
